/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as CareerRouteImport } from './routes/career'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FutureRouteImport } from './routes/future'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as MediaSplatRouteImport } from './routes/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/career': typeof CareerRoute
  '/finance': typeof FinanceRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/memories': typeof MemoriesRoute
  '/missions': typeof MissionsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/todos': typeof TodosRoute
  '/widget': typeof WidgetRoute
  '/media/$': typeof MediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/career': typeof CareerRoute
  '/finance': typeof FinanceRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/memories': typeof MemoriesRoute
  '/missions': typeof MissionsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/todos': typeof TodosRoute
  '/widget': typeof WidgetRoute
  '/media/$': typeof MediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/career': typeof CareerRoute
  '/finance': typeof FinanceRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/memories': typeof MemoriesRoute
  '/missions': typeof MissionsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/todos': typeof TodosRoute
  '/widget': typeof WidgetRoute
  '/media/$': typeof MediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/career'
    | '/finance'
    | '/future'
    | '/journey'
    | '/memories'
    | '/missions'
    | '/reviews'
    | '/settings'
    | '/skills'
    | '/todos'
    | '/widget'
    | '/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/career'
    | '/finance'
    | '/future'
    | '/journey'
    | '/memories'
    | '/missions'
    | '/reviews'
    | '/settings'
    | '/skills'
    | '/todos'
    | '/widget'
    | '/media/$'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/career'
    | '/finance'
    | '/future'
    | '/journey'
    | '/memories'
    | '/missions'
    | '/reviews'
    | '/settings'
    | '/skills'
    | '/todos'
    | '/widget'
    | '/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CareerRoute: typeof CareerRoute
  FinanceRoute: typeof FinanceRoute
  FutureRoute: typeof FutureRoute
  JourneyRoute: typeof JourneyRoute
  MemoriesRoute: typeof MemoriesRoute
  MissionsRoute: typeof MissionsRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TodosRoute: typeof TodosRoute
  WidgetRoute: typeof WidgetRoute
  MediaSplatRoute: typeof MediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CareerRoute: CareerRoute,
  FinanceRoute: FinanceRoute,
  FutureRoute: FutureRoute,
  JourneyRoute: JourneyRoute,
  MemoriesRoute: MemoriesRoute,
  MissionsRoute: MissionsRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TodosRoute: TodosRoute,
  WidgetRoute: WidgetRoute,
  MediaSplatRoute: MediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
